server:
  middleware:
    - type: recovery
    - type: logging
    - type: request_id

routes:
  - path: /users/{id}
    method: GET
    checks:
      - type: inject
        config:
          ctx:
            service_name: gateway
    transform:
      header:
        X-Service-Name: context.service_name
    upstream:
      url: https://jsonplaceholder.typicode.com/users
      method: GET