routes:
  - path: /users
    method: GET
    upstream: 
        url: https://jsonplaceholder.typicode.com/users
        method: GET
    checks:
      - type: auth
        config: 
          url: http://localhost:8080/ping
          method: GET
          expected_status: 200

  - path: /posts
    method: GET
    upstream: 
        url: https://jsonplaceholder.typicode.com/posts
        method: GET
